//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimAcher.Infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALUNO()
        {
            this.ALUNO_APRENDER = new HashSet<ALUNO_APRENDER>();
            this.ALUNO_ENSINAR = new HashSet<ALUNO_ENSINAR>();
            this.ALUNO_GOSTO = new HashSet<ALUNO_GOSTO>();
        }
    
        public string login { get; set; }
        public string nome { get; set; }
        public System.DateTime dt_nascimento { get; set; }
        public int telefone { get; set; }
        public string e_mail { get; set; }
        public System.Data.Entity.Spatial.DbGeography geolocalizacao { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUNO_APRENDER> ALUNO_APRENDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUNO_ENSINAR> ALUNO_ENSINAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUNO_GOSTO> ALUNO_GOSTO { get; set; }
    }
}
