//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimAcher.Infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ALUNO_APRENDER
    {
        public int cod_aa { get; set; }
        public int cod_al { get; set; }
        public int cod_a { get; set; }
    
        public virtual MA_ALUNO MA_ALUNO { get; set; }
        public virtual MA_APRENDER MA_APRENDER { get; set; }
    }
}
