//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimAcher.Infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_IMAGEM_USUARIO
    {
        public int cod_i { get; set; }
        public byte[] imagem { get; set; }
        public int cod_us { get; set; }
    
        public virtual MA_USUARIO MA_USUARIO { get; set; }
    }
}
