//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimAcher.Infra
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIMACHEREntities : DbContext
    {
        public MIMACHEREntities()
            : base("name=MIMACHEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MA_ALUNO> MA_ALUNO { get; set; }
        public virtual DbSet<MA_ALUNO_APRENDER> MA_ALUNO_APRENDER { get; set; }
        public virtual DbSet<MA_ALUNO_ENSINAR> MA_ALUNO_ENSINAR { get; set; }
        public virtual DbSet<MA_ALUNO_GOSTO> MA_ALUNO_GOSTO { get; set; }
        public virtual DbSet<MA_APRENDER> MA_APRENDER { get; set; }
        public virtual DbSet<MA_ENSINAR> MA_ENSINAR { get; set; }
        public virtual DbSet<MA_GOSTO> MA_GOSTO { get; set; }
        public virtual DbSet<MA_IMAGEM_USUARIO> MA_IMAGEM_USUARIO { get; set; }
        public virtual DbSet<MA_NAC_CAMPUS> MA_NAC_CAMPUS { get; set; }
        public virtual DbSet<MA_USUARIO> MA_USUARIO { get; set; }
    }
}
