//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimAcher.Infra
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIMACHEREntities : DbContext
    {
        public MIMACHEREntities()
            : base("name=MIMACHEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUNO> ALUNO { get; set; }
        public virtual DbSet<ALUNO_APRENDER> ALUNO_APRENDER { get; set; }
        public virtual DbSet<ALUNO_ENSINAR> ALUNO_ENSINAR { get; set; }
        public virtual DbSet<ALUNO_GOSTO> ALUNO_GOSTO { get; set; }
        public virtual DbSet<APRENDER> APRENDER { get; set; }
        public virtual DbSet<ENSINAR> ENSINAR { get; set; }
        public virtual DbSet<GOSTO> GOSTO { get; set; }
        public virtual DbSet<IMAGEM_USUARIO> IMAGEM_USUARIO { get; set; }
        public virtual DbSet<NAC_CAMPUS> NAC_CAMPUS { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
