//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimAcher.Infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAC_CAMPUS
    {
        public string login { get; set; }
        public string nome_representante { get; set; }
        public System.Data.Entity.Spatial.DbGeography geolocalizacao { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
