//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimAcher.Infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.IMAGEM_USUARIO = new HashSet<IMAGEM_USUARIO>();
        }
    
        public string login { get; set; }
        public string senha { get; set; }
        public int identificador { get; set; }
    
        public virtual ALUNO ALUNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGEM_USUARIO> IMAGEM_USUARIO { get; set; }
        public virtual NAC_CAMPUS NAC_CAMPUS { get; set; }
    }
}
