//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace MimAcher.Dominio
{
    public partial class MA_CAMPUS
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MA_CAMPUS()
        {
            this.MA_NAC = new HashSet<MA_NAC>();
            this.MA_PARTICIPANTE = new HashSet<MA_PARTICIPANTE>();
        }
    
        public int cod_campus { get; set; }
        public string local { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_NAC> MA_NAC { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_PARTICIPANTE> MA_PARTICIPANTE { get; set; }
    }
}
