//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimAcher.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ERRO
    {
        public int cod_erro { get; set; }
        public string tipo { get; set; }
        public string aconteceu { get; set; }
        public int incidencia { get; set; }
        public Nullable<System.DateTime> dt_acontecimento { get; set; }
    }
}
