//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace MimAcher.Dominio
{
    public partial class MA_NAC
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MA_NAC()
        {
            this.MA_NAC_AREA_ATUACAO = new HashSet<MA_NAC_AREA_ATUACAO>();
        }
    
        public int cod_nac { get; set; }
        public int cod_usuario { get; set; }
        public int cod_campus { get; set; }
        public string nome_representante { get; set; }
        public int telefone { get; set; }
    
        public virtual MA_CAMPUS MA_CAMPUS { get; set; }
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_NAC_AREA_ATUACAO> MA_NAC_AREA_ATUACAO { get; set; }
        public virtual MA_USUARIO MA_USUARIO { get; set; }
    }
}
