//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MimAcher.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PARTICIPANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MA_PARTICIPANTE()
        {
            this.MA_IMAGEM_PARTICIPANTE = new HashSet<MA_IMAGEM_PARTICIPANTE>();
        }
    
        public int cod_participante { get; set; }
        public int cod_usuario { get; set; }
        public int cod_campus { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public System.DateTime dt_nascimento { get; set; }
        public System.Data.Entity.Spatial.DbGeography geolocalizacao { get; set; }
    
        public virtual MA_CAMPUS MA_CAMPUS { get; set; }
        public virtual MA_USUARIO MA_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_IMAGEM_PARTICIPANTE> MA_IMAGEM_PARTICIPANTE { get; set; }
    }
}
