#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MimAcher.Resource", IsApplication=true)]

namespace MimAcher
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int escolherfoto = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fundo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int losango = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int mais = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int MimAcherIconBig = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int round_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int selector_check = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060030
			public const int Buttonsline = 2131099696;
			
			// aapt resource value: 0x7f060011
			public const int Logo = 2131099665;
			
			// aapt resource value: 0x7f060027
			public const int Nome_line = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int Senha_line = 2131099685;
			
			// aapt resource value: 0x7f060023
			public const int Usuario_line = 2131099683;
			
			// aapt resource value: 0x7f06000f
			public const int alterar_senha = 2131099663;
			
			// aapt resource value: 0x7f06001f
			public const int analise_sistemas = 2131099679;
			
			// aapt resource value: 0x7f06003b
			public const int angular_js = 2131099707;
			
			// aapt resource value: 0x7f06002e
			public const int avançar = 2131099694;
			
			// aapt resource value: 0x7f060013
			public const int avançar2 = 2131099667;
			
			// aapt resource value: 0x7f060005
			public const int confirmar = 2131099653;
			
			// aapt resource value: 0x7f06003c
			public const int dota2 = 2131099708;
			
			// aapt resource value: 0x7f060028
			public const int email = 2131099688;
			
			// aapt resource value: 0x7f06004d
			public const int email_info = 2131099725;
			
			// aapt resource value: 0x7f06000c
			public const int email_info_user = 2131099660;
			
			// aapt resource value: 0x7f060029
			public const int email_line = 2131099689;
			
			// aapt resource value: 0x7f06004c
			public const int email_result = 2131099724;
			
			// aapt resource value: 0x7f06000b
			public const int email_user = 2131099659;
			
			// aapt resource value: 0x7f06001d
			public const int empreender = 2131099677;
			
			// aapt resource value: 0x7f06002f
			public const int entrar = 2131099695;
			
			// aapt resource value: 0x7f060012
			public const int exibirfoto = 2131099666;
			
			// aapt resource value: 0x7f06001a
			public const int futebol = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int games = 2131099673;
			
			// aapt resource value: 0x7f06002a
			public const int idade = 2131099690;
			
			// aapt resource value: 0x7f06000e
			public const int idade_info_user = 2131099662;
			
			// aapt resource value: 0x7f06002b
			public const int idade_line = 2131099691;
			
			// aapt resource value: 0x7f06000d
			public const int idade_user = 2131099661;
			
			// aapt resource value: 0x7f060031
			public const int inscrevase = 2131099697;
			
			// aapt resource value: 0x7f060000
			public const int logo = 2131099648;
			
			// aapt resource value: 0x7f06003a
			public const int mobile = 2131099706;
			
			// aapt resource value: 0x7f060016
			public const int name_user_line1 = 2131099670;
			
			// aapt resource value: 0x7f060049
			public const int name_user_line13 = 2131099721;
			
			// aapt resource value: 0x7f060008
			public const int name_user_line14 = 2131099656;
			
			// aapt resource value: 0x7f060041
			public const int name_user_line2 = 2131099713;
			
			// aapt resource value: 0x7f060034
			public const int name_user_line3 = 2131099700;
			
			// aapt resource value: 0x7f060046
			public const int name_user_line8 = 2131099718;
			
			// aapt resource value: 0x7f060026
			public const int nome = 2131099686;
			
			// aapt resource value: 0x7f060015
			public const int nome_user1 = 2131099669;
			
			// aapt resource value: 0x7f060048
			public const int nome_user13 = 2131099720;
			
			// aapt resource value: 0x7f060007
			public const int nome_user14 = 2131099655;
			
			// aapt resource value: 0x7f060040
			public const int nome_user2 = 2131099712;
			
			// aapt resource value: 0x7f060033
			public const int nome_user3 = 2131099699;
			
			// aapt resource value: 0x7f060045
			public const int nome_user_result = 2131099717;
			
			// aapt resource value: 0x7f060001
			public const int nova_senha = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int nova_senha_line = 2131099650;
			
			// aapt resource value: 0x7f060035
			public const int o_que_vc_aprender = 2131099701;
			
			// aapt resource value: 0x7f060042
			public const int o_que_vc_ensinar = 2131099714;
			
			// aapt resource value: 0x7f060017
			public const int o_que_vc_gosta = 2131099671;
			
			// aapt resource value: 0x7f060021
			public const int ok1 = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int outros1 = 2131099680;
			
			// aapt resource value: 0x7f06003e
			public const int outros2 = 2131099710;
			
			// aapt resource value: 0x7f060043
			public const int outros3 = 2131099715;
			
			// aapt resource value: 0x7f06003d
			public const int php = 2131099709;
			
			// aapt resource value: 0x7f060037
			public const int poker = 2131099703;
			
			// aapt resource value: 0x7f06001b
			public const int pop = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int programacao = 2131099676;
			
			// aapt resource value: 0x7f060003
			public const int repita_nova_senha = 2131099651;
			
			// aapt resource value: 0x7f060018
			public const int rock = 2131099672;
			
			// aapt resource value: 0x7f060004
			public const int rs_line = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int salvar = 2131099664;
			
			// aapt resource value: 0x7f060024
			public const int senha = 2131099684;
			
			// aapt resource value: 0x7f06004b
			public const int tel_number = 2131099723;
			
			// aapt resource value: 0x7f06000a
			public const int tel_number_user = 2131099658;
			
			// aapt resource value: 0x7f06002c
			public const int telefone = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int telefone_line = 2131099693;
			
			// aapt resource value: 0x7f06004a
			public const int telefone_result = 2131099722;
			
			// aapt resource value: 0x7f060009
			public const int telefone_user = 2131099657;
			
			// aapt resource value: 0x7f060022
			public const int usuario = 2131099682;
			
			// aapt resource value: 0x7f06001e
			public const int viajar = 2131099678;
			
			// aapt resource value: 0x7f060014
			public const int view_image1 = 2131099668;
			
			// aapt resource value: 0x7f060047
			public const int view_image13 = 2131099719;
			
			// aapt resource value: 0x7f060006
			public const int view_image14 = 2131099654;
			
			// aapt resource value: 0x7f06003f
			public const int view_image2 = 2131099711;
			
			// aapt resource value: 0x7f060032
			public const int view_image3 = 2131099698;
			
			// aapt resource value: 0x7f060044
			public const int view_image8 = 2131099716;
			
			// aapt resource value: 0x7f060036
			public const int violao = 2131099702;
			
			// aapt resource value: 0x7f060039
			public const int violino = 2131099705;
			
			// aapt resource value: 0x7f060038
			public const int xadrez = 2131099704;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlterarSenha = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditarPerfil = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EscolherFoto = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Gostos = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Inscrever = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int QueroAprender = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int QueroEnsinar = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Resultado = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int UsuarioResultado = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
